[features]
resolution = true
skip-lint = false

# Replace with your deployed program id after `anchor keys list` / `solana-keygen`.
[programs.localnet]
slotto_lottery = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFTE24"

[programs.devnet]
slotto_lottery = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFTE24"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor build"
